/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.client.view;

import chat.client.controller.ClientController;
import chat.client.controller.ChatController;
import chat.data.model.Contact;
import chat.data.model.Group;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author sharno
 */
public class StartGroupChat extends javax.swing.JDialog {

    Map<Contact, Boolean> contactsMap = new HashMap<>();
    ContactsListView contactsListView;
    /**
     * Creates new form StartGroupChat
     */
    public StartGroupChat(ContactsListView contactsListView, boolean modal) {
        super(contactsListView, modal);
        
        this.contactsListView = contactsListView;
        for (Group group : ChatController.groupsList) {
            if (group.getContacts().size() == 2) {
                for (Contact contact : group.getContacts()) {
                    if (contact.getId() != ClientController.userId) {
                        contactsMap.put(contact, false);
                    }
                }
            }
        }

        initComponents();

//        DefaultListModel<Contact> contactsListModel = new DefaultListModel<Contact>();
//        contactsList.setModel(contactsListModel);
        contactsList.setListData(new Vector(contactsMap.keySet()));
        contactsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        contactsList.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
//                int index = contactsList.locationToIndex(e.getPoint());
                Contact contact = (Contact)contactsList.getSelectedValue();
                boolean selected = ! (contactsMap.get(contact));
                contactsMap.replace(contact, selected);
                contactsList.repaint();
            }
            
        });
        contactsList.setCellRenderer(new ListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Contact contact = (Contact) value;
                JCheckBox checkBox = new JCheckBox();
                
                checkBox.setText(contact.getFname() + " " + contact.getLname() + " (" + contact.getEmail() + ")");
                checkBox.setSelected(contactsMap.get(contact));
                return checkBox;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contactsList = new JList<Contact>();
        createGroupChatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contactsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(contactsList);

        createGroupChatButton.setText("Create group chat");
        createGroupChatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupChatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(createGroupChatButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(createGroupChatButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createGroupChatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupChatButtonActionPerformed
        Vector<Contact> groupContacts = new Vector<>();
        for (Map.Entry<Contact, Boolean> entry : contactsMap.entrySet()) {
            if (entry.getValue()) {
                groupContacts.add(entry.getKey());
            }
        }
        
        contactsListView.createGroupChat(groupContacts);
    }//GEN-LAST:event_createGroupChatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StartGroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StartGroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StartGroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StartGroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                StartGroupChat dialog = new StartGroupChat(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList contactsList;
    private javax.swing.JButton createGroupChatButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
